[versions]
agp = "8.7.1"
roktsdk = "4.6.0"

[libraries]
roktsdk = { module = "com.rokt:roktsdk", version.ref = "roktsdk" }

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "2.0.21" }
android-library = { id = "com.android.library", version.ref = "agp" }

